/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.0.9 scene.gltf
Author: Warkarma (https://sketchfab.com/warkarma)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chess-day-4-3december-960dc43d8e4848178c81201535f45be3
Title: Chess - Day 4 - 3December
*/

import React, { useRef, FC } from "react";
import { useGLTF } from "@react-three/drei";
import { ChessPieceColors, ChessPieceProps } from "../ChessPieceManager";

export const QueenPiece: FC<ChessPieceProps> = ({
  color,
  position = [0, 0.5, 0],
}) => {
  const { nodes, materials } = useGLTF("/assets/chess/scene.gltf");
  return (
    <group dispose={null} scale={0.05}>
      {color === ChessPieceColors.BLACK ? (
        <group position={position}>
          <mesh
            geometry={(nodes as any).Object_10.geometry}
            material={materials.Black_Piece}
          />
          <mesh
            geometry={(nodes as any).Object_11.geometry}
            material={materials.White_Piece}
          />
        </group>
      ) : (
        <group position={position}>
          <mesh
            geometry={(nodes as any).Object_22.geometry}
            material={materials.White_Piece}
          />
          <mesh
            geometry={(nodes as any).Object_23.geometry}
            material={materials.Black_Piece}
          />
        </group>
      )}
    </group>
  );
};

useGLTF.preload("/assets/chess/scene.gltf");
