/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.0.9 scene.gltf
Author: Warkarma (https://sketchfab.com/warkarma)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chess-day-4-3december-960dc43d8e4848178c81201535f45be3
Title: Chess - Day 4 - 3December
*/

import React, { useRef, FC } from "react";
import { useGLTF } from "@react-three/drei";
import { ChessPieceColors, ChessPieceProps } from "../ChessPieceManager";
import { useBox, useCylinder } from "@react-three/cannon";
import { DoubleSide, Group, Mesh } from "three";
import { useFrame } from "@react-three/fiber";
import { CHESS_ASSET_SCALE } from "../../types/textures";

export const QueenPiece: FC<ChessPieceProps> = ({
  color,
  position = [0, 1, 0],
}) => {
  const { nodes, materials } = useGLTF("/assets/chess/scene.gltf");

  const [ref] = useCylinder(
    () => ({
      args: [0.07, 0.12, 0.5],
      rotation: [0, 0, 0],
      position,
      mass: 0.1,
      allowSleep: true,
      sleepSpeedLimit: 0.07,
      sleepTimeLimit: 0.01,
    }),
    useRef<Group>(null!)
  );

  return (
    <group dispose={null} scale={CHESS_ASSET_SCALE} ref={ref}>
      {color === ChessPieceColors.BLACK ? (
        <group>
          <mesh
            position={[0, -0.75, 0]}
            castShadow
            geometry={(nodes as any).Object_10.geometry}
            material={materials.Black_Piece}
          />
          <mesh
            position={[0, -0.75, 0]}
            castShadow
            geometry={(nodes as any).Object_11.geometry}
            material={materials.White_Piece}
          />
        </group>
      ) : (
        <group>
          <mesh
            position={[0, -0.75, 0]}
            castShadow
            geometry={(nodes as any).Object_22.geometry}
            material={materials.White_Piece}
          />
          <mesh
            position={[0, -0.75, 0]}
            castShadow
            geometry={(nodes as any).Object_23.geometry}
            material={materials.Black_Piece}
          />
        </group>
      )}
    </group>
  );
};

useGLTF.preload("/assets/chess/scene.gltf");
