/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.0.9 scene.gltf
Author: Warkarma (https://sketchfab.com/warkarma)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chess-day-4-3december-960dc43d8e4848178c81201535f45be3
Title: Chess - Day 4 - 3December
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useBox } from "@react-three/cannon";
import { DoubleSide, Group, Mesh } from "three";

export function ChessBoard() {
  const { nodes, materials } = useGLTF("/assets/chess/scene.gltf");

  const [chessBoardRef] = useBox(
    () => ({
      args: [0.45, 0.06, 0.45],
      rotation: [0, -Math.PI / 2, 0],
    }),
    useRef<Group>(null!)
  );

  return (
    <group dispose={null} ref={chessBoardRef} scale={0.05}>
      <mesh
        receiveShadow
        castShadow
        geometry={(nodes as any).Object_4.geometry}
        material={materials.Board}
        position={[0, 0, 0]}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={(nodes as any).Object_20.geometry}
        material={materials.Board}
        position={[0, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/assets/chess/scene.gltf");
