/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.0.9 scene.gltf
Author: Warkarma (https://sketchfab.com/warkarma)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chess-day-4-3december-960dc43d8e4848178c81201535f45be3
Title: Chess - Day 4 - 3December
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function ChessBoard(props) {
  const { nodes, materials } = useGLTF("/assets/chess/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.05}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_4.geometry}
            material={materials.Board}
            position={[0, 0, 0]}
          />
          <mesh
            geometry={nodes.Object_20.geometry}
            material={materials.Board}
            position={[0, 0, 0]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/assets/chess/scene.gltf");
