/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.0.9 scene.gltf
Author: Alex Bes (https://sketchfab.com/alexbescg)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/worn-baseball-ball-fdf3de6ae225421ea78961b897b9608a
Title: Worn Baseball Ball
*/

import React, { FC, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useSphere } from "@react-three/cannon";
import { DoubleSide, Group, Mesh } from "three";

type BaseballProps = {
  position?: [number, number, number];
  radius?: number;
};

const Baseball: FC<BaseballProps> = ({
  position = [0, 0.5, 0],
  radius = 1,
}) => {
  const { nodes, materials } = useGLTF("/assets/baseball/scene.gltf");

  const [ballRef] = useSphere(
    () => ({
      args: [0.42 * radius],
      position,
      mass: 0.5,
      allowSleep: true,
    }),
    useRef<Group>(null!)
  );

  return (
    <group dispose={null} ref={ballRef} scale={radius}>
      <mesh
        castShadow
        geometry={(nodes as any).polySurface5_lambert1_0.geometry}
        material={materials.lambert1}
        rotation={[0, 0, 0]}
      />
    </group>
  );
};

useGLTF.preload("/assets/baseball/scene.gltf");

export default Baseball;
