/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.0.9 scene.gltf
Author: MSerdar Tekin (https://sketchfab.com/teriologia)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bowling-pin-028ccb945012460aa9056ffda5b53e20
Title: Bowling Pin
*/

import React, { FC, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useBox } from "@react-three/cannon";
import { Mesh, Group } from "three";

export type PinProps = {
  size: [number, number, number];
  segments?: [number, number];
  rotation?: [number, number, number];
  position?: [number, number, number];
  mass?: number;
};

const Pin: FC<PinProps> = ({ size, ...props }) => {
  const { nodes, materials } = useGLTF("/assets/bowling_pin/edited-pin.gltf");
  const [pinRef] = useBox(
    () => ({ args: [size[0], size[1] * 2, size[2]], ...props }),
    useRef<Group>(null!)
  );

  console.log({ nodes, materials });
  return (
    <group dispose={null} ref={pinRef}>
      <mesh
        scale={[7 * size[0], 7 * size[1], 7 * size[2]]}
        geometry={(nodes as any).Object_4.geometry}
        material={materials.material}
      />
      <mesh
        scale={[7 * size[0], 7 * size[1], 7 * size[2]]}
        geometry={(nodes as any).Object_5.geometry}
        material={materials.PinStripe}
      />
    </group>
  );
};

useGLTF.preload("/assets/bowling_pin/edited-pin.gltf");

export default Pin;
