/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.0.9 scene.gltf
Author: Warkarma (https://sketchfab.com/warkarma)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chess-day-4-3december-960dc43d8e4848178c81201535f45be3
Title: Chess - Day 4 - 3December
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.04}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.51, 0.22, 3.5]}>
            <mesh geometry={nodes.Object_10.geometry} material={materials.Black_Piece} />
            <mesh geometry={nodes.Object_11.geometry} material={materials.White_Piece} />
          </group>
          <group position={[3.52, 0.22, -0.49]}>
            <mesh geometry={nodes.Object_13.geometry} material={materials.Black_Piece} />
            <mesh geometry={nodes.Object_14.geometry} material={materials.White_Piece} />
          </group>
          <group position={[-3.49, 0.22, -0.46]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.Object_22.geometry} material={materials.White_Piece} />
            <mesh geometry={nodes.Object_23.geometry} material={materials.Black_Piece} />
          </group>
          <group position={[-3.47, 0.22, 2.52]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.Object_25.geometry} material={materials.White_Piece} />
            <mesh geometry={nodes.Object_26.geometry} material={materials.Black_Piece} />
          </group>
          <mesh geometry={nodes.Object_4.geometry} material={materials.Board} position={[0.01, -0.38, 0]} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.Black_Piece} position={[2.5, 0.22, 3.51]} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.Black_Piece} position={[3.55, 0.22, 3.51]} />
          <mesh geometry={nodes.Object_16.geometry} material={materials.Black_Piece} position={[2.54, 0.22, 0.43]} />
          <mesh geometry={nodes.Object_18.geometry} material={materials.Black_Piece} position={[3.52, 0.22, 2.51]} />
          <mesh geometry={nodes.Object_20.geometry} material={materials.Board} position={[0.01, -0.38, 0]} />
          <mesh geometry={nodes.Object_28.geometry} material={materials.White_Piece} position={[-1.57, 0.22, 3.57]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.Object_30.geometry} material={materials.White_Piece} position={[0.56, 0.22, 0.5]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.Object_32.geometry} material={materials.White_Piece} position={[-3.52, 0.22, 1.45]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.Object_34.geometry} material={materials.White_Piece} position={[-2.54, 0.22, 3.49]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.Object_36.geometry} material={materials.White_Piece} position={[1.52, 0.22, -0.48]} rotation={[Math.PI, -1.48, Math.PI]} />
          <mesh geometry={nodes.Object_38.geometry} material={materials.White_Piece} position={[-3.47, 0.22, -2.48]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.Object_40.geometry} material={materials.White_Piece} position={[-2.5, 0.22, -3.44]} rotation={[Math.PI, -1.13, Math.PI]} />
          <mesh geometry={nodes.Object_42.geometry} material={materials.White_Piece} position={[-1.49, 0.22, 2.51]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.Object_44.geometry} material={materials.White_Piece} position={[-0.46, 0.22, 1.5]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.Object_46.geometry} material={materials.White_Piece} position={[-0.51, 0.22, 0.45]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.Object_48.geometry} material={materials.White_Piece} position={[-1.45, 0.22, -0.46]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.Object_50.geometry} material={materials.White_Piece} position={[6.22, -0.02, -2.51]} rotation={[2.17, 0.19, -1.03]} />
          <mesh geometry={nodes.Object_52.geometry} material={materials.White_Piece} position={[-0.5, 0.22, -1.51]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.Object_54.geometry} material={materials.White_Piece} position={[-0.5, 0.22, -3.52]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.Object_56.geometry} material={materials.Black_Piece} position={[3.5, 0.22, -1.45]} rotation={[-Math.PI, 1.41, -Math.PI]} />
          <mesh geometry={nodes.Object_58.geometry} material={materials.Black_Piece} position={[2.46, 0.22, -0.51]} />
          <mesh geometry={nodes.Object_60.geometry} material={materials.Black_Piece} position={[0.65, 0.22, 2.45]} />
          <mesh geometry={nodes.Object_62.geometry} material={materials.Black_Piece} position={[1.49, 0.22, 1.44]} />
          <mesh geometry={nodes.Object_64.geometry} material={materials.Black_Piece} position={[3.5, 0.22, -3.5]} rotation={[0, Math.PI / 4, 0]} />
          <mesh geometry={nodes.Object_66.geometry} material={materials.Black_Piece} position={[-7.08, -0.02, 1.78]} rotation={[-1.34, 0.35, 2.96]} />
          <mesh geometry={nodes.Object_68.geometry} material={materials.Black_Piece} position={[-6.23, -0.02, -0.78]} rotation={[-0.4, 0.06, 1.78]} />
          <mesh geometry={nodes.Object_70.geometry} material={materials.Black_Piece} position={[0.55, 0.22, -2.43]} />
          <mesh geometry={nodes.Object_72.geometry} material={materials.Black_Piece} position={[2.54, 0.22, -2.53]} />
          <mesh geometry={nodes.Object_74.geometry} material={materials.Black_Piece} position={[1.53, 0.22, -3.51]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
